CREATE DATABASE IF NOT EXISTS LOJA_CELULAR;
USE LOJA_CELULAR;

CREATE TABLE IF NOT EXISTS PRODUTO(
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOME_PRODUTO VARCHAR(20) NOT NULL UNIQUE,
  MARCA_PRODUTO VARCHAR(20) NOT NULL,
  PRECO_PRODUTO DECIMAL(6,2) NOT NULL
  );

CREATE TABLE IF NOT EXISTS FORNECEDOR(
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOME_FORNECEDOR VARCHAR(20) NOT NULL UNIQUE,
  TELEFONE_FORNECEDOR VARCHAR(20) NOT NULL,
  RUA_FORNECEDOR VARCHAR(20) NOT NULL,
  NUMERO_FORNECEDOR VARCHAR(20) NOT NULL,
  BAIRRO_FORNECEDOR VARCHAR(20) NOT NULL,
  CIDADE_FORNECEDOR VARCHAR(20) NOT NULL,
  UF_FORNECEDOR VARCHAR(2) NOT NULL
);

CREATE TABLE IF NOT EXISTS DEPOSITO(
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOME_DEPOSITO VARCHAR(20) NOT NULL UNIQUE,
  TELEFONE_DEPOSITO VARCHAR(20) NOT NULL,
  RUA_DEPOSITO VARCHAR(20) NOT NULL,
  NUMERO_DEPOSITO VARCHAR(20) NOT NULL,
  BAIRRO_DEPOSITO VARCHAR(20) NOT NULL,
  CIDADE_DEPOSITO VARCHAR(20) NOT NULL,
  UF_DEPOSITO VARCHAR(2) NOT NULL
);


CREATE TABLE IF NOT EXISTS FORNECEDOR_PRODUTO(
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ID_FORNECEDOR INT NOT NULL,
  ID_PRODUTO INT NOT NULL,
  CONSTRAINT FK_ID_FORNECEDOR_FP FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDOR (ID),
  CONSTRAINT FK_ID_PRODUTO_FP FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID)
);

CREATE TABLE IF NOT EXISTS DEPOSITO_PRODUTO(
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ID_DEPOSITO INT NOT NULL,
  ID_PRODUTO INT NOT NULL,
  PONTO_REPOSICAO INT NOT NULL,
  QTD_ATUAL INT NOT NULL,
  CONSTRAINT FK_ID_DEPOSITO_DP FOREIGN KEY (ID_DEPOSITO) REFERENCES DEPOSITO (ID),
  CONSTRAINT FK_ID_PRODUTO_DP FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO (ID)
);

CREATE TABLE IF NOT EXISTS MOVIMENTACAO (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ID_DEPOSITO INT NOT NULL,
  ID_PRODUTO INT NOT NULL,
  QTD_MOVIMENTACAO INT NOT NULL,
  TIPO_MOVIMENTACAO INT NOT NULL,
  CONSTRAINT FK_ID_DEPOSITO_M FOREIGN KEY (ID_DEPOSITO) REFERENCES DEPOSITO (ID),
  CONSTRAINT FK_ID_PRODUTO_M FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO (ID)
);
